#!/usr/bin/env php
<?php

declare(strict_types=1);

use Yiisoft\Yii\Runner\Console\ConsoleApplicationRunner;

require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/config/dotenv-setup.php';

if (\function_exists('setEnvironmentVariables')) {
    setEnvironmentVariables();
}

// Run console application runner
$runner = new ConsoleApplicationRunner(
    rootPath: __DIR__,
    debug: $_ENV['YII_DEBUG'],
    checkEvents: $_ENV['YII_DEBUG'],
    environment: $_ENV['YII_ENV'],
);

$runner->run();
