#!/usr/bin/env php
<?php

declare(strict_types=1);

use Yii\Framework\Runner\ConsoleApplication;

require_once __DIR__ . '/vendor/autoload.php';


/**
 * Run console application runner.
 */
(new ConsoleApplication())->withRootPath(__DIR__)->run();
